version: '3'
services:
  mongo:
    image: mongo
  redis:
    image: redis
  worker:
    image: airtraffic24
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
    command: sidekiq -r ./app/worker.rb
  receiver:
    image: airtraffic24
    depends_on:
      - worker
    volumes:
      - .:/app
    ports:
      - "1234:1234/udp"
    command: ruby /app/at24.rb
