version: '2'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db

  receiver:
    image: airtraffic24
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - .:/app
    command: ruby /app/at24.rb
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"

  api:
    image: airtraffic24
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ruby /app/api.rb
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"

  nginx:
    image: airtraffic24-nginx
    depends_on:
      - rabbitmq
      - api
    volumes:
      - ./data/sites:/etc/nginx/sites-enabled
      - ./data/letsencrypt:/etc/letsencrypt
    links:
      - rabbitmq
      - api
    ports:
      - 443:443
      - 80:80

